<?php

return apply_filters( 'micro_posts_post_type_args', array(
    'label'                 => __( 'Micro Post', 'micro-posts' ),
    'labels'                => array(
        'name'                  => _x( 'Micro Posts', 'Post Type General Name', 'micro-posts' ),
        'singular_name'         => _x( 'Micro Post', 'Post Type Singular Name', 'micro-posts' ),
        'menu_name'             => __( 'Micro Posts', 'micro-posts' ),
        'name_admin_bar'        => __( 'Micro Post', 'micro-posts' ),
        'archives'              => __( 'Micro Post Archives', 'micro-posts' ),
        'attributes'            => __( 'Micro Post Attributes', 'micro-posts' ),
        'parent_item_colon'     => __( '', 'micro-posts' ),
        'all_items'             => __( 'All Micro Posts', 'micro-posts' ),
        'add_new_item'          => __( 'Add New Micro Post', 'micro-posts' ),
        'add_new'               => __( 'Add New', 'micro-posts' ),
        'new_item'              => __( 'New Micro Post', 'micro-posts' ),
        'edit_item'             => __( 'Edit Micro Post', 'micro-posts' ),
        'update_item'           => __( 'Update Micro Post', 'micro-posts' ),
        'view_item'             => __( 'View Micro Post', 'micro-posts' ),
        'view_items'            => __( 'View Micro Posts', 'micro-posts' ),
        'search_items'          => __( 'Search Micro Post', 'micro-posts' ),
        'not_found'             => __( 'Not found', 'micro-posts' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'micro-posts' ),
        'featured_image'        => __( 'Featured Image', 'micro-posts' ),
        'set_featured_image'    => __( 'Set featured image', 'micro-posts' ),
        'remove_featured_image' => __( 'Remove featured image', 'micro-posts' ),
        'use_featured_image'    => __( 'Use as featured image', 'micro-posts' ),
        'insert_into_item'      => __( 'Insert into Micro Post', 'micro-posts' ),
        'uploaded_to_this_item' => __( 'Uploaded to this Micro Post', 'micro-posts' ),
        'items_list'            => __( 'Micro Posts list', 'micro-posts' ),
        'items_list_navigation' => __( 'Micro Posts list navigation', 'micro-posts' ),
        'filter_items_list'     => __( 'Filter Micro Posts list', 'micro-posts' ),
    ),
    'supports'              => array( 'editor', 'comments' ),
//    'taxonomies'            => array( 'category', 'post_tag' ),
    'hierarchical'          => false,
    'public'                => true,
    'show_ui'               => true,
    'show_in_menu'          => true,
    'menu_position'         => 5,
    'show_in_admin_bar'     => true,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => true,
    'exclude_from_search'   => false,
    'publicly_queryable'    => true,
    'capability_type'       => 'post',
    'show_in_rest'          => true,
) );
